[package]
name = "tablestream"
version = "0.1.0"
edition = "2018"
readme = "README.md"


[dependencies]
# Used to determine terminal width.
# (And maybe eventually for colors.)
crossterm = "*"

[dev-dependencies.structopt]
# Used by example.rs
version = "*"